### ISSUE TITLE
关于暗黑模式的几个小问题

### ISSUE THREAD

**Issue by zsbai** [HongyuS/Bilibili-Mac#1]
macOS12.3.1
1. 在软件设置中打开跟随系统模式之后重启也没有效果，还是只能手动更改主题
2. 视频播放界面的主题和主页面不一致，视频播放页面一直是暗黑模式

另一个疑问，在设置中设置允许软件传入网络连接，但每次打开软件还是会弹窗询问 “是否 允许软件传入网络”

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/62942942/168467770-d9c1593b-a2ec-434e-9a94-101795b8c5dd.png">

**Comment by yhl452493373** [comment]
这里的所有问题估计都得去官方反馈了。我windows装上了和mac一样的问题

**Comment by zsbai** [comment]
> 这里的所有问题估计都得去官方反馈了。我windows装上了和mac一样的问题

看起来确实是这样😂那我先把这个issue关闭吧

**Comment by HongyuS** [comment]
关于“是否 允许软件传入网络”，没签名的app都有这个问题，只有“符合苹果认证”的app会遵守设置里的选项

但私下移植的非官方版显然不会有苹果的认证（我公开发布私自认证的版本会有版权问题，所以打算低调一点）

**Comment by zsbai** [comment]
> 关于“是否 允许软件传入网络”，没签名的app都有这个问题，只有“符合苹果认证”的app会遵守设置里的选项
> 
> 但私下移植的非官方版显然不会有苹果的认证（我公开发布私自认证的版本会有版权问题，所以打算低调一点）

啊好的 可以理解😂
