### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by coressss** [HongyuS/Bilibili-Mac#3]
11.6.5系统登录不上，扫码和接收验证码均无法登陆，具体为点击登陆后登陆窗口消失但是没有登录成功，不知道和开了代理有没有关系

**Comment by long2ice** [comment]
我这边可以正常登录

**Comment by coressss** [comment]
好，可能是挂代理的问题



来自 meizu 17 Pro



-------- 原始邮件 --------
发件人：long2ice ***@***.***>
时间：2022年5月16日 10:22
收件人：HongyuS/Bilibili-Mac ***@***.***>
抄送：coressss ***@***.***>,Author ***@***.***>
主题：Re: [HongyuS/Bilibili-Mac] 登录不上 (Issue #3)


我这边可以正常登录
